### github-action-variable-01.yml

name: Test Github Actions variable-01
on:
  push

env:
  Day_OF_WEEK: Friday



jobs:
  check-var-01:
    runs-on: ubuntu-latest
    steps:
      - name: "It's Day!"
        run: echo "Today is $Day_OF_WEEK!"
